### ISSUE TITLE
Bash Shell: writing basic scripts

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-bash-writing-scripts-old#1]
Scripts, variables, and loops []
Functions in bash []
Using bash scripts in pipes []

**Comment by PipGrylls** [comment]
Scripts, Vars, Loops: @PipGrylls Light Edit
Functions: @PipGrylls From Scratch
Bash scripts in pipes: @smangham From Scratch

**Comment by phillybroadbent** [comment]
Scripts, variables and loops
•	Shell variables – could add that setting a variable only work with no spaces around the =
•	Could remind the learner how to edit the shell script demo.sh
•	Loops - Could prompt to save the file as loops.sh before creating it

**Comment by steve-crouch** [comment]
Merged into updated repo at https://github.com/Southampton-RSG-Training/dirac-bash-command-line
